### PR TITLE
Add contact form validation

### PR DESCRIPTION
**Pull request by mhassa204**
Contact form validation has been added. The email is validated if the email is capital letters the form will show an error message, otherwise if the email is in lowercase the form will be submitted. I have commented the final submission of form and instead i have placed an alert message if the email is validated.

### CODE REVIEW

**Review by LionRouge1 — COMMENTED** [review]
Hi @mhassa204, 

done

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that was supposed to be a pair-programming activity but you're the only one who contributed to the project. Kindly work with your partner to submit this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by frank1738 — COMMENTED** [review]
Hi @mhassa204 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Kindly ensure that your partner contributes to the project as this is a pair programming milestone.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by topeogunleye — COMMENTED** [review]
Hi @mhassa204, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a pair programming project with no contributions from your partner.  Kindly report any issue you had with your partner to the `student success` team and they'll permit you to work solo or look for a suitable partner. Attach a screenshot of the message you received from `student success` stating that you can do the project alone in the pull request description and resubmit this PR👍

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Comment by enniopo** [comment]
Note for the CR: the student has no coding partner for this week. Therefore he is allowed to work solo on the project. 
Please proceed with the review.

**Review by topeogunleye — COMMENTED** [review]
Hi @mhassa204,

Great job on completing your contact form project! 🎉 You've successfully met the project requirements and demonstrated a solid understanding of JavaScript, HTML, and CSS. Here's a detailed review of your project: There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

dwayne-the-rock

## (Highlights) Good Points: 💪 

Linting and Repository Organization:
Your project's repository is well-organized and adheres to best practices. The correct setup of JavaScript and HTML&CSS linters indicates a commitment to maintaining clean and error-free code. This attention to detail contributes to the overall quality of your project. 👍

Email Format Validation:
Your implementation of email format validation showcases a thoughtful approach to user input. By checking if the email is written in all lowercase, you've addressed a crucial aspect of data validation. The error message's placement close to the submit button or input fields ensures a seamless user experience. 👏

Event Handling and Validation Logic:
Your use of the form "submit" event or submit button/input "click" event to trigger the email format validation function is a practical choice. This approach demonstrates your understanding of event handling in JavaScript. Implementing the check for lowercase email characters using methods like comparison, regular expressions, or looping shows your versatility in problem-solving. 🚀

JavaScript Best Practices:
Your JavaScript code follows best practices, contributing to code readability and maintainability. The logical flow of your code and efficient implementation of email format validation indicate your proficiency in JavaScript programming. Your code is well-structured and easy to understand. 💻

In conclusion, your contact form project reflects a strong grasp of coding fundamentals, user input validation, and event handling in JavaScript. Your attention to detail, use of best practices, and commitment to creating a user-friendly experience are highly commendable. Keep up the excellent work, and continue expanding your skills and knowledge in web development. If you have any questions or need further guidance, don't hesitate to reach out.

Congratulations on a job well done! 🌟

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- For future pull requests, please notice that your branch name `form-validation` does not follow the convention of being named after a feature or action. For example, you could name your branch `added-form-validation`. This makes it easier to track the changes and the purpose of each branch.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
